import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";
import {Provider} from 'react-redux'
// import store from '@/app/Store'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

<html lang="en">
      <body className={inter.className}>
      {/* <Provider store={store} > */}
        <Navbar />
        <div className="">
        {children}
        </div>
        <Footer />
{/* </Provider> */}

      </body>
    </html>
  );
}
